### ISSUE TITLE
Update the data preparation in the Wiki

### ISSUE THREAD

**Issue by schakalakka** [DLR-VF/TAPAS#43]
Please update the [wiki](https://github.com/DLR-VF/TAPAS/wiki/Data-Preparation) data prepration section for the 
- locations @mariald
- travel time matrices @aschengen 
- population @avonschmidt 
- diaries @schakalakka 

You can use the [Data Preparation page](https://github.com/DLR-VF/TAPAS/wiki/Data-Preparation) or create extra pages in the wiki if you like. 

You can look at the information from our old wiki [here](https://wiki.dlr.de/display/MUD/Datenbereitstellung) or (better) take the information from your new paper.

**Comment by schakalakka** [comment]
@MHeinrichs 
- modechoice 
please add chapter to the above wiki page

**Comment by schakalakka** [comment]
Information about diary groups added.

**Comment by mariald** [comment]
Information about locations added.

**Comment by aschengen** [comment]
general information about matrices inside TAPAS added. Closing the issue.
